### ISSUE TITLE
Add other planning software to the end of the document

### ISSUE THREAD

**Issue by meneguzzi** [pucrs-automated-planning/pddl-formalization#2]
@Maumagnaguagno, can you add links to other planners you know of that could be used to test this domain? You could (and should) add the site of Dovetail there when it's online.

**Comment by meneguzzi** [comment]
BTW, it's the last section in the document, so it should be easy to find.

**Comment by Maumagnaguagno** [comment]
We should add instructions and dependencies too, like GCC/Java version and supported OS.
Otherwise students may lose time installing and compiling stuff that will never work in their environment.

Already tested and added planning.domains with instructions.
I need to check which other planners can deal with basic requirements before adding them.

**Comment by meneguzzi** [comment]
Agreed, go ahead and include them as you find them.
