### ISSUE TITLE
Add instructions to use Dovetail as a markdown file

### ISSUE THREAD

**Issue by meneguzzi** [pucrs-automated-planning/pddl-formalization#3]
Once Dovetail is online, you should add another Markdown file explaining how to use it.

**Comment by Maumagnaguagno** [comment]
This sounds like usage documentation to be available in a help button in the tool itself.
Such help button already exists and opens a modal box where detailed information will be displayed, it is currently empty.
This is not a big problem since we have the tool starting with a complete example with lots of comments about PDDL and its limitations (requirements).
I will add more files or link related to the usage experience to evaluate the tool itself.

**Comment by meneguzzi** [comment]
True, but I reckon we should include the instructions of usage according to the experiment protocol (i.e. the stuff we will add to the paper stating that these were the formally supplied instructions). Maybe this should be the same instructions in the tool, but I reckon we should add some kind of post-usage survey text here.
